name: 'build docker file'
description: 'this action will create a docker repository in ecr and set policy'
inputs:
  aws-role-arn:
    description: 'AWS Role ARN'
    required: true
  codeartifact-auth-token:
    description: 'CodeArtifact Authentication Token'
    required: true
  service-name:
    description: 'the name of the service. mostly should be the name of the repo'
    required: false
    default: ${{ github.event.repository.name }}
  account_id:
    description: 'the account number of aws'
    required: false
    default: '974360507615'
  repository_name:
    description: 'name of the ecr repository. preferable: github repository name and service name'
    required: true
    default: ${{ github.event.repository.name }}
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: create.docker.repository.sh ${{ inputs.account_id }} ${{ inputs.repository_name }}
      shell: bash
